const image = (id) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=800&q=80`;

export const guideListings = [
	{
		type: 'guide',
		title: 'Manipur Culture & Nature Guide',
		name: 'Manipur Culture & Nature Guide',
		description: 'Local guide offering heritage walks, food trails and nature trips across Manipur.',
		bio: 'A local guide helping visitors experience Manipur through its heritage, food, lakes and hills.',
		district: 'Imphal West',
		location: 'Imphal',
		languages: ['English', 'Hindi', 'Meitei'],
		specializations: ['Heritage', 'Food', 'Nature'],
		experience: 8,
		pricePerDay: 1800,
		responseRate: 96,
		responseTime: 'Within 1 hour',
		verified: true,
		featured: true,
		tours: [
			{
				id: 'culture-walk',
				title: 'Imphal Heritage Walk',
				description: 'Kangla and nearby cultural sites.',
				duration: '4 hours',
				price: 900,
				includes: ['Local guide', 'History briefing'],
			},
		],
		coordinates: { lat: 24.817, lng: 93.936 },
		images: [image('photo-1507003211169-0a1dd7228f8d')],
		avatar: image('photo-1507003211169-0a1dd7228f8d'),
		rating: 4.9,
		reviewCount: 61,
	},
	{
		type: 'guide',
		title: 'Loktak Lake & Moirang Guide',
		name: 'Loktak Lake & Moirang Guide',
		description: 'Explore Loktak Lake, floating phumdis, local food and the stories of Moirang.',
		bio: 'A community-based guide from Moirang sharing responsible ways to experience Loktak Lake.',
		district: 'Bishnupur',
		location: 'Moirang',
		languages: ['Meitei', 'English', 'Hindi'],
		specializations: ['Loktak Lake', 'Boating', 'Culture'],
		experience: 6,
		pricePerDay: 1600,
		responseRate: 94,
		responseTime: 'Within 2 hours',
		verified: true,
		featured: true,
		tours: [],
		coordinates: { lat: 24.552, lng: 93.786 },
		images: [image('photo-1470770841072-f978cf4d019e')],
		avatar: image('photo-1470770841072-f978cf4d019e'),
		rating: 4.8,
		reviewCount: 38,
	},
];
